### ISSUE TITLE
Possible Bug when using CharRNNEmbedder

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#492]
My current issue its I'm trying to do a sequence tagging of ordinals
and when I try to predict 1º will give me a wrong tag but if I add 3 padding_values more 
creating the sequence 1 º <blank> <blank> <blank>
then the prediction is the correct one.
since its everything done in batch the sample 1º will always contain padding_values.

Taking a look into the code the sequence_lenght of the characters is ignored from tokens_to_chars func and we use the tf.count_nonzero to count the <blank> id which will always work if we use the create vocabulary from opennmt (I find this behavior a little bit hidden)
the point is maybe is there something not selecting correctly the end of the character sequence?

right know I'm using CharRNNEmbedder with SpaceTokenizer, because I want to embbed the data of the characters for each word

**Comment by guillaumekln** [comment]
I think the issue comes from the default encoding strategy which is "average": it will give incorrect results on variable length tensors. If that's indeed the issue, there are 2 possible solutions:

* Use encoding "last" (which should probably be the default...)
* Take the mean of a [RaggedTensor], see for example the [MeanEncoder implementation](https://github.com/OpenNMT/OpenNMT-tf/blob/master/opennmt/encoders/mean_encoder.py)

**Comment by lockder** [comment]
yes right know I'm using average as encoding. I will retrain and tell you

**Comment by lockder** [comment]
@guillaumekln I tested it, using "last" as encoding works 100% of the time

**Comment by guillaumekln** [comment]
In v2, we actually removed the "average" encoding. As you also have a simple workaround, I think we can close this issue.
