### ISSUE TITLE
Question about BLEU evaluation

### ISSUE THREAD

**Issue by Embedding** [OpenNMT/OpenNMT-tf#91]
This project is extremely useful to me, thanks for your great work.
I use external evaluator BLEU and BLEU-detok in opennmt-tf to evaluate our seq2seq model. The returned result is 2.21/1.96 for BLEU/BLEU-detok. However, when I use another popular BLEU script for evaluation (https://github.com/xinyadu/nqg/blob/master/qgevalcap/bleu/bleu_scorer.py), the returned results are Bleu1: 0.263 Bleu2: 0.10017 Bleu3: 0.04796 Bleu4: 0.026. I can not figure out why the BLEU in opennmt is much less than BLEU in https://github.com/xinyadu/nqg/blob/master/qgevalcap/bleu/bleu_scorer.py

**Comment by guillaumekln** [comment]
I don't know about the BLEU script you referenced. It's likely popular because it is written in Python.

However, the BLEU et BLEU-detok evaluators in OpenNMT-tf use `multi-bleu.perl` and `multi-bleu-detok.perl` respectively. In particular, when the later is executed on detokenized output it produces the same result as `mteval-v13a.pl` which is commonly used to report BLEU scores in research papers.

**Comment by Embedding** [comment]
Thank you very much for your kind suggestion.
